######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 17:03:05
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/OvuleCell2DGrowth_234567_stiffUniform100_MMC_notDividingFromTime110.mdxm', 'no', 'no', '0')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '190', 'Mesh/System/Save', 'OvuleCell2DGrowth_234567_stiffUniform100', '200')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 17:03:46
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '190', 'Mesh/System/Save', 'OvuleCell2DGrowth_234567_MMC_notDividingTime110', '200')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 17:08:35
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/OvuleCell2DGrowth_234567_stiffUniform100_MMC_notDividingFromTime110.mdxm', 'no', 'no', '0')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/CellDisk.mdxv')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '80', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-MMC_notdividingFromTme110', '81')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 17:25:11
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/OvuleCell2DGrowth_234567_stiffUniform100_MMC_notDividingFromTime110_pressure0d2MMC.mdxm', 'no', 'no', '0')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '80', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-MMC_notdividingFromTme110_MMCPress0d2', '81')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 18:29:00
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/comparisonImageSettingFinalPaperMMC_notDivromT110.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/OvuleCell2DGrowth_MS-Case2-0190.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/OvuleCell2DGrowth_MS-MMC_notdividingFromTme110-0080.mdxm', 'no', 'no', '1')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/comparisonImageSettingFinalPaperMMC_notDivromT110.mdxv')
