######## New MorphoDynamX session v2.0 r2-672-gb342f639: 2020-01-13 23:47:39

Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-672-gb342f639: 2020-01-16 15:57:21
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/regulardGridPolygonizedAssignedPressurized_234567.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-16 16:06:32
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-16 19:11:45
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/OvuleCell2DGrowth_NotDividingSMC_110_pressure0d2_from110-0093.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('', 'No', 'No', '1')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/massSpringSimulations/cleanedModels/case2/OvuleCell2DGrowth_234567_stiffUniform100-0100.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/massSpringSimulations/cleanedModels/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-16 19:23:39
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-16 20:02:29
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-23 18:03:45
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-26 19:27:06
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-29 18:54:53
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 09:22:58
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case7/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 11:41:42
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('', 'No', 'No', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 12:01:19
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_234567/comparisonImageSetting.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 12:35:56
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/OvuleCell2DGrowth_234567_stiffUniform100-0190.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 12:42:38
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 12:53:26
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 13:00:34
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case4/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 14:04:25
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case5/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 14:15:59
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case5/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 14:31:46
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case5/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 14:38:07
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case5/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 14:58:11
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case6/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 15:04:03
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case6/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 15:26:58
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case6/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 15:40:10
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case7/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 15:46:54
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case8/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 15:53:45
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case8/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 16:04:09
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/L1onlySignalBasedGrowth/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 16:11:09
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/L1onlySignalBasedGrowth/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 16:29:28
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/L1OnlyStrainBasedGrowth0d5/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 16:37:04
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/noDifferentialAreaL2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 17:02:59
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 17:03:36
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 17:08:13
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/OvuleCell2DGrowth_234567_stiffUniform100_MMC_notDividingFromTime110.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 17:25:05
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 17:27:59
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/realTemplate/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 17:35:28
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/realTemplate/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 17:41:22
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 18:01:54
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/comparisonImageSettingFinalPaper.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_234567/OvuleCell2DGrowth_234567_stiffUniform100-0170.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_23567/OvuleCell2DGrowth_23567_stiffUniform100-0170.mdxm', 'no', 'no', '1')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/comparisonImageSettingFinalPaper.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 18:33:40
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 18:40:48
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case6/comparisonImageSettingFinalPaperCase6.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-24 16:17:56
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/regulardGridPolygonizedAssignedPressurized_234567.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-24 16:20:16
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/comparisonImageSettingFinalPaper.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_234567/OvuleCell2DGrowth_234567_stiffUniform100-0170.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_23567/OvuleCell2DGrowth_23567_stiffUniform100-0170.mdxm', 'no', 'no', '1')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-28 15:05:21
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('100.0', '100.0', '4', '360', 'Polygon')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__System__Reset('0')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('100.0', '200', '4', '360', 'Polygon')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/rectangle100x200.mdxm', 'No', '0')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('300', '200', '4', '360', 'Polygon')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/square200.mdxm', 'No', '0')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/rectangle300x200.mdxm', 'No', '0')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-28 15:14:29
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-28 15:22:33
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-28 15:27:50
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('', 'No', 'No', '0')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('1', 'Polarizer')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__d_Solver_Diffusion_for_Polarizer('10', '0.01', '.0001', '10', '10', '10', 'Euler', 'Bi-conjugate Gradient Stabilized', '50', '1e-6', 'Yes', '.1', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/30 Growth Process/c Diffusion for Polarizer')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('1', 'Polarizer')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__d_Solver_Diffusion_for_Polarizer('10', '0.01', '.0001', '10', '10', '10', 'Euler', 'Bi-conjugate Gradient Stabilized', '50', '1e-6', 'Yes', '.1', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/30 Growth Process/c Diffusion for Polarizer')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__e_Polarizer_Vector_Render('Draw Polarizer', 'Yes', '1.0')
Process.Mesh__Segmentation__Relabel_Cells('1', '1')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__d_Solver_Diffusion_for_Polarizer('10', '0.01', '.0001', '10', '10', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '50', '1e-6', 'Yes', '.1', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/30 Growth Process/c Diffusion for Polarizer')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('1', 'Polarizer')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__e_Polarizer_Vector_Render('Draw Polarizer', 'Yes', '1.0')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('1', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '10')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/square100.mdxm', 'No', 'No', '0')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__d_Solver_Diffusion_for_Polarizer('10', '0.01', '.0001', '10', '10', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '50', '1e-6', 'Yes', '.1', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/30 Growth Process/c Diffusion for Polarizer')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.5', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__e_Polarizer_Vector_Render('Draw Polarizer', 'Yes', '1.0')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/rectangle100x200.mdxm', 'No', 'No', '0')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('1', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Visualize_Assigned_Cell_Properties('Cell Type')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.5', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('2', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Visualize_Assigned_Cell_Properties('Cell Type')
Process.Model__Cell_Ovule_Growth__50_Visualize_Assigned_Cell_Properties('Cell Type')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('10', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('50', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.1', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.01', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.1', 'Polarizer')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.1', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.01', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.01', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Visualize_Assigned_Cell_Properties('Cell Type')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.01', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.0001', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Visualize_Assigned_Cell_Properties('Cell Type')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-28 16:18:13
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('', 'No', 'No', '0')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__d_Solver_Diffusion_for_Polarizer('10', '0.01', '.0001', '10', '10', '10', 'Euler', 'Bi-conjugate Gradient Stabilized', '50', '1e-6', 'Yes', '.1', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/30 Growth Process/c Diffusion for Polarizer')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.5', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.01', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('1', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('5', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-28 16:37:20
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('', 'No', 'No', '0')
Process.Mesh__Segmentation__Relabel_Cells('1', '1')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.5', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.001', 'Intrinsic')
Process.Mesh__Structure__Transform_Mesh('0.0 0.0 0.0', '0 0 1', '30', '1.0')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/rectangle100x200.mdxm', 'No', '0')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.001', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/rectangle100x20rotated0.mdxm', 'No', 'No', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/square200.mdxm', 'No', 'No', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/square200.mdxm', 'No', 'No', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/square300.mdxm', 'No', 'No', '0')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('300', '300', '4', '360', 'Polygon')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/square300.mdxm', 'No', '0')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('200', '200', '4', '360', 'Polygon')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('200', '200', '4', '360', 'Polygon')
Process.Mesh__System__Reset('0')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('200', '200', '4', '360', 'Polygon')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Mesh__System__Save('', 'No', '0')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/square200.mdxm', 'No', 'No', '0')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__00_Global_Shape_Quantifier_Process('Model/Cell Ovule Growth/50 Shape Quantifier/01 Compute Skey Symmetric Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/02 Compute Antisymmetry Tensor', 'Model/Cell Ovule Growth/50 Shape Quantifier/03 Visualize Shape Field')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.001', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.1', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.01', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-688: 2020-02-28 17:13:30
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('', 'No', 'No', '0')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.1', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '1.0')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-688: 2020-02-28 17:19:37
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('100.0', '110', '4', '360', 'Polygon')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.1', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('100.0', '120', '4', '360', 'Polygon')
Process.Mesh__System__Reset('0')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('100.0', '120', '4', '360', 'Polygon')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.1', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('100.0', '110', '4', '360', 'Polygon')
Process.Mesh__System__Reset('0')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('100.0', '110', '4', '360', 'Polygon')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.1', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-688: 2020-02-29 18:27:54
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__Cell_Maker__Mesh_2D__Shapes__Polygon('200', '400', '4', '360', 'Polygon')
Process.Mesh__Segmentation__Relabel_Faces('1', '1')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__a_Set_Fixed_Concentr_Diffusion_Polarizer__Assign('1.')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.01', 'Intrinsic')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '100')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-688: 2020-03-01 15:08:30
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/square100.mdxm', 'no', 'no', '0')
Process.Tools__Cell_Maker__Mesh_3D__Shapes__Platonic_Solid('Cube (6 sides)', '200.0')
Process.Tools__Cell_Maker__Tools__Triangulate_Faces('10.0')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/square100.mdxm', 'No', '0')
Process.Mesh__System__Delete_Cell_Complex('Platonic Solid Triangulated')
Process.Mesh__System__Delete_Cell_Complex('Platonic Solid')
Process.Tools__Cell_Maker__Mesh_3D__From_2D_Mesh__Extrude_Faces('300', '1', '1', '0', 'Cells')
Process.Tools__Cell_Maker__Tools__Triangulate_Faces('10.0')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/cube100.mdxm', 'No', '0')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-04-27 22:21:46
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-04-30 00:38:06
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/OvuleCell2DGrowth_34567_uniforStiffness_L1AnisotropicGrowth-0058.mdxm', 'no', 'no', '0')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__01_Compute_Skey_Symmetric_Tensor('0.5', 'Polarizer')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '1.0')
Process.Model__Cell_Ovule_Growth__50_Shape_Quantifier__03_Visualize_Shape_Field('Anisotropy', 'Draw cell anisotropy', '5')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__d_Solver_Diffusion_for_Polarizer('10', '0.01', '.0001', '10', '10', '10', 'Euler', 'Bi-conjugate Gradient Stabilized', '50', '1e-6', 'Yes', '.1', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/30 Growth Process/c Diffusion for Polarizer')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__e_Polarizer_Vector_Render('Draw Polarizer', 'Yes', '1.0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/OvuleCell2DGrowth_MS-Case2-0058.mdxm', 'no', 'no', '0')
Process.Model__Cell_Ovule_Growth__30_Growth_Process__e_Polarizer_Vector_Render('Draw Polarizer', 'Yes', '1.0')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-05-04 19:12:31
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case7/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-05-04 19:17:44
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case7/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-05-05 11:39:43
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-05-05 12:01:22
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-05-05 12:09:35
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-08 22:34:06
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_2xStiffer/regulardGridPolygonizedAssignedNoPressurized_234567.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_2xStiffer/CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-08 22:47:53
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/comparisonImageSettingFinalPaper.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/comparisonImageSettingFinalPaper.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_23567/OvuleCell2DGrowth_23567_stiffUniform100-0170.mdxm', 'no', 'no', '1')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_234567/OvuleCell2DGrowth_234567_stiffUniform100-0170.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_0d5Stiffness/regulardGridPolygonizedAssignedNoPressurized_234567.mdxm', 'no', 'no', '0')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__c_Set_Wall_Stiffness__Reset()
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_0d5Stiffness/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-08 22:57:24
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_0d5Stiffness/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-08 23:11:56
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_80Stiffnes/regulardGridPolygonizedAssignedNoPressurized_234567_Ey200.mdxm', 'no', 'no', '0')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__c_Set_Wall_Stiffness__Reset()
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_80Stiffnes/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-08 23:24:58
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_90Stiffness/regulardGridPolygonizedAssignedPressurized_234567_stiffn90.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_90Stiffness/CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-08 23:35:04
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/comparisonImageSettingFinalPaper.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_234567/OvuleCell2DGrowth_234567_stiffUniform100-0170.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_234567/OvuleCell2DGrowth_234567_stiffUniform100-0170.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_23567/OvuleCell2DGrowth_23567_stiffUniform100-0170.mdxm', 'no', 'no', '1')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_110Stiffness/regulardGridPolygonizedAssignedNoPressurized_234567.mdxm', 'no', 'no', '0')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__b_Set_Cell_Type_Mechanics_and_Growth__Reset()
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__c_Set_Wall_Stiffness__Reset()
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_110Stiffness/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-08 23:42:34
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_110Stiffness/CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-08 23:47:51
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/comparisonImageSettingFinalPaper.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_23567/OvuleCell2DGrowth_23567_stiffUniform100-0170.mdxm', 'no', 'no', '1')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_234567/OvuleCell2DGrowth_234567_stiffUniform100-0170.mdxm', 'no', 'no', '0')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/comparisonImageSettingFinalPaper.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-08 23:58:11
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_growthSign0d18/regulardGridPolygonizedAssignedPressurized_234567.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_growthSign0d18/CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-09 00:04:54
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/comparisonImageSettingFinalPaper.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_110Stiffness/OvuleCell2DGrowth_MS-Case2_stiffness110-0190.mdxm', 'no', 'no', '1')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-09 00:06:55
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_growthSign0d22/regulardGridPolygonizedAssignedPressurized_234567_growthSign0d18.mdxm', 'no', 'no', '0')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__a_Set_Cell_Type__Assign('Source Cell', '0.22', 'True', 'False')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_growthSign0d22/CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-09 00:12:27
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/comparisonImageSettingFinalPaper.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_110Stiffness/OvuleCell2DGrowth_MS-Case2_stiffness110-0190.mdxm', 'no', 'no', '1')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-09 00:14:18
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_growthSign0d22/regulardGridPolygonizedAssignedPressurized_234567_growthSign0d18.mdxm', 'no', 'no', '0')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__a_Set_Cell_Type__Assign('Ground Cell', '0.22', 'True', 'False')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/robustness_analysis_growthSign0d22/regulardGridPolygonizedAssignedPressurized_234567_growthSign0d18.mdxm', 'No', '0')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-714: 2020-06-29 21:04:14
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/noDifferentialAreaL2/comparisonImageSettingFinalPaperNoDifferentialAreaL2.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-714: 2020-06-30 22:42:29
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-719: 2020-07-01 10:22:18
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-719: 2020-07-01 10:23:27
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-719: 2020-07-06 17:33:58
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-719: 2020-07-06 17:36:55
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-727: 2020-07-24 13:52:31
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-727: 2020-07-24 20:41:25
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-727: 2020-07-26 12:04:18
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/mesh-2018_2404_275aSegmentedMeshMergingSplittingNonGrowingPoligonizedAssignedPressurized_latest.mdxm', 'no', 'no', '0')
Process.Mesh__System__Render('', '', 'Yes', 'No', 'Yes', 'No', 'Yes', '0.8', '3', '3', '0.02', '128 128 128 255')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/OvuleCell2DGrowthRealTemplate_MMC_100_L150-0108.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/OvuleCell2DGrowthRealTemplate_MMC_100_L150-0136.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/OvuleCell2DGrowthRealTemplate_MMC_100_L150-0159.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-727: 2020-07-26 12:17:20
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/CellDisk.mdxv')
Process.Tools__System__Load_View('CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-727: 2020-07-27 14:45:07
Process.Tools__System__Load_View('CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case4/OvuleCell2DGrowt_MS-Case4-0050.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case5/OvuleCell2DGrowth_MS-Case5-0168.mdxm', 'no', 'no', '0')
