######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 18:32:33
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/withMegaSpore/comparisonImageSettingFinalPaperMMC_notDivromT110.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/mesh-2018_2404_275aSegmentedMeshMergingSplittingNonGrowingPoligonizedAssignedPressurized_latest.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-719: 2020-07-01 10:22:35
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '159', 'Mesh/System/Save', 'OvuleCell2DGrowthRealTemplate_MMC_100_L150', '160')
######## New MorphoDynamX session v2.0 r2-719: 2020-07-01 10:23:33
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '159', 'Mesh/System/Save', 'OvuleCell2DGrowthRealTemplate_MMC_100_L150', '160')
######## New MorphoDynamX session v2.0 r2-719: 2020-07-06 17:37:53
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '108, 114, 136', 'Mesh/System/Save', 'OvuleCell2DGrowthRealTemplate_MMC_100_L150', '160')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/OvuleCell2DGrowthRealTemplate_MMC_100_L150-0108.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/OvuleCell2DGrowthRealTemplate_MMC_100_L150-0114.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/OvuleCell2DGrowthRealTemplate_MMC_100_L150-0136.mdxm', 'no', 'no', '0')
######## New MorphoDynamX session v2.0 r2-727: 2020-07-26 12:11:19
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/CellDisk.mdxv')
Process.Mesh__System__Render('', '', 'Yes', 'No', 'Yes', 'No', 'Yes', '0.8', '3', '3', '0.02', '128 128 128 255')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '159', 'Mesh/System/Save', 'OvuleCell2DGrowthRealTemplate_MMC_100_L150', '160')
######## New MorphoDynamX session v2.0 r2-727: 2020-07-26 12:17:24
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/CellDisk.mdxv')
Process.Mesh__System__Render('', '', 'Yes', 'No', 'Yes', 'No', 'Yes', '0.8', '3', '3', '0.02', '128 128 128 255')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '150', 'Mesh/System/Save', 'OvuleCell2DGrowthRealTemplate_MMC_100_L150', '160')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/realTemplate/OvuleCell2DGrowthRealTemplate_MMC_100_L150-0150.mdxm', 'no', 'no', '0')
