######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 11:56:18
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/massSpringSimulations/veryFinaleSetPaper/case_234567/comparisonImageSetting.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 12:53:41
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case3', '200')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__a_Set_Cell_Type__Assign('Ground Cell', '0', 'Yes', 'False')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__a_Set_Cell_Type__Assign('Ground Cell', '0.2', 'Yes', 'False')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case3', '200')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 18:04:03
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/comparisonImageSettingFinalPaper.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/OvuleCell2DGrowth_MS-Case2-0190.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/OvuleCell2DGrowth_MS-Case3-0190.mdxm', 'no', 'no', '1')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/comparisonImageSettingFinalPaperCase3.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 18:36:50
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/comparisonImageSettingFinalPaperCase3.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/OvuleCell2DGrowth_MS-Case2-0190.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/OvuleCell2DGrowth_MS-Case3-0190.mdxm', 'no', 'no', '1')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/comparisonImageSettingFinalPaperCase3.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-04-27 22:21:58
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '10, 46, 47, 58, 100, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_34567_uniforStiffness_L1AnisotropicGrowth', '200')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__a_Set_Cell_Type__Assign('Ground Cell', '0.2', 'Yes', 'False')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '10, 46, 47, 58, 100, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_34567_uniforStiffness_L1AnisotropicGrowth', '200')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '10, 46, 47, 58, 100, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_34567_uniforStiffness_L1AnisotropicGrowth', '200')
######## New MorphoDynamX session v2.0 r2-689: 2020-05-05 12:10:52
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '10, 46, 47, 58, 100, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_34567_uniforStiffness_L1AnisotropicGrowth', '200')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__a_Set_Cell_Type__Assign('Ground Cell', '0.2', 'Yes', 'False')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__c_Growth_Signal_Solver('1', '0.01', '.0001', '0.1', '0.01', '100', 'Adaptive Euler', 'Bi-conjugate Gradient Stabilized', '50', '1.e-10', 'Yes', '1.e-8', 'Model/Cell Ovule Growth/10 Growth Signal/b Growth Signal Gradient', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '10, 46, 47, 58, 100, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_34567_uniforStiffness_L1AnisotropicGrowth', '200')
