######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 15:47:01
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case8/CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case8/CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case8/regulardGridPolygonizedAssignedPressurized_onlyL1sources.mdxm', 'no', 'no', '0')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case8/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 100, 160, 350', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case8', '351')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 15:53:57
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case8/CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case8/CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case8/regulardGridPolygonizedAssignedPressurized_onlyL1Signal.mdxm', 'no', 'no', '0')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case8/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 100, 160, 350', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case8', '351')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 18:15:32
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case7/comparisonImageSettingFinalPaperCase7.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/OvuleCell2DGrowth_MS-Case2-0190.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case8/OvuleCell2DGrowth_MS-Case8-0350.mdxm', 'no', 'no', '1')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case8/comparisonImageSettingFinalPaperCase8.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/L1onlySignalBasedGrowth/comparisonImageSettingFinalPaperL1OnlySignalBasedGr.mdxv')
