######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-23 18:04:10
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/regulardGridPolygonizedAssignedPressurized_234567.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/regulardGridPolygonizedAssignedNoPressurized_234567.mdxm', 'no', 'no', '0')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__a_Set_Dirichlet('0 0 0 ', '0 0 0', 'Dirichlet Attribute')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__f_Mass_Spring_Solver('1', '0.1', '1.e-6', '1', '5', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '100', '1.e-20', 'Yes', '0.01', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/e Mass Spring Parameters')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__c_Set_Wall_Stiffness__Assign('100', 'False', '100', '100', 'Negative', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/b Growth Signal Gradient')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__c_Set_Wall_Stiffness__Assign('100', 'False', '100', '100', 'Negative', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/b Growth Signal Gradient')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__f_Mass_Spring_Solver('1', '0.1', '1.e-6', '1', '5', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '100', '1.e-20', 'Yes', '0.01', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/e Mass Spring Parameters')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__c_Set_Wall_Stiffness__Assign('100', 'False', '100', '100', 'Negative', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/b Growth Signal Gradient')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__f_Mass_Spring_Solver('1', '0.1', '1.e-6', '1', '5', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '100', '1.e-20', 'Yes', '0.01', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/e Mass Spring Parameters')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__a_Set_Dirichlet('0 0 0 ', '0 0 0', 'Dirichlet Attribute')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__a_Set_Dirichlet('1 0 1', '0 0 0', 'Dirichlet Attribute')
Process.Model__Cell_Ovule_Growth__20_Mass_Spring_Mechanics__f_Mass_Spring_Solver('1', '0.1', '1.e-6', '1', '5', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '100', '1.e-20', 'Yes', '0.01', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/e Mass Spring Parameters')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-26 19:27:15
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-29 18:55:03
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '190', 'Mesh/System/Save', 'OvuleCell2DGrowth_234567_stiffUniform100', '200')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__a_Set_Cell_Type__Assign('Ground Cell', '0.2', 'Yes', 'False')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '190', 'Mesh/System/Save', 'OvuleCell2DGrowth_234567_stiffUniform100', '200')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 11:55:58
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case3/CellDisk.mdxv')
Process.Tools__System__Load_View('')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/OvuleCell2DGrowth_234567_stiffUniform100-0190.mdxm', 'no', 'no', '0')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 12:36:37
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 89, 160, 170, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 12:43:37
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 89, 160, 170, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 89, 160, 170, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 89, 160, 170, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__a_Set_Cell_Type__Assign('Ground Cell', '0.2', 'Yes', 'False')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__a_Set_Cell_Type__Assign('Ground Cell', '0.2', 'Yes', 'False')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 89, 160, 170, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 17:41:32
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '49, 159, 168', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '170')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-01-30 18:33:45
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '150', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '151')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-24 16:18:17
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '58', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '59')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/model/comparisonImageSettingFinalPaper.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-05-05 11:39:51
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 89, 160, 170, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
######## New MorphoDynamX session v2.0 r2-689: 2020-05-05 12:01:39
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 89, 160, 170, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__a_Set_Cell_Type__Assign('Ground Cell', '0.2', 'Yes', 'False')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__c_Growth_Signal_Solver('1', '0.01', '.0001', '0.1', '0.01', '100', 'Adaptive Euler', 'Bi-conjugate Gradient Stabilized', '50', '1.e-10', 'Yes', '1.e-8', 'Model/Cell Ovule Growth/10 Growth Signal/b Growth Signal Gradient', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 89, 160, 170, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__a_Set_Cell_Type__Assign('Ground Cell', '0.2', 'Yes', 'False')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__c_Growth_Signal_Solver('1', '0.01', '.0001', '0.1', '0.01', '100', 'Adaptive Euler', 'Bi-conjugate Gradient Stabilized', '50', '1.e-10', 'Yes', '1.e-8', 'Model/Cell Ovule Growth/10 Growth Signal/b Growth Signal Gradient', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 89, 160, 170, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
######## New MorphoDynamX session v2.0 r2-714: 2020-06-30 22:42:45
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 89, 160, 170, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
######## New MorphoDynamX session v2.0 r2-719: 2020-07-06 17:34:11
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '134', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/OvuleCell2DGrowth_MS-Case2-0134.mdxm', 'no', 'no', '0')
######## New MorphoDynamX session v2.0 r2-727: 2020-07-24 13:52:37
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/git_repoMassSpring2D/MassSpring_2DovuleGrowthModel/case2/CellDisk.mdxv')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 89, 160, 170, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__a_Set_Cell_Type__Assign('Ground Cell', '0.2', 'Yes', 'False')
Process.Model__Cell_Ovule_Growth__10_Growth_Signal__c_Growth_Signal_Solver('1', '0.01', '.0001', '0.1', '0.01', '100', 'Adaptive Euler', 'Bi-conjugate Gradient Stabilized', '50', '1.e-10', 'Yes', '1.e-8', 'Model/Cell Ovule Growth/10 Growth Signal/b Growth Signal Gradient', 'Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process')
Process.Model__Cell_Ovule_Growth__00_Ovule_Master_Process('Model/Cell Ovule Growth/40 Cell Tissue/a Cell Tissue Process', 'Model/Cell Ovule Growth/10 Growth Signal/c Growth Signal Solver', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/c Set Wall Stiffness/Assign', 'Model/Cell Ovule Growth/30 Growth Process/d Solver Diffusion for Polarizer', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/f Mass Spring Solver', 'Model/Cell Ovule Growth/30 Growth Process/b Mass Spring Growth', 'Model/Cell Ovule Growth/40 Cell Tissue/b Divide Cells', 'Model/Cell Ovule Growth/40 Cell Tissue/c Split Edges', 'Model/Cell Ovule Growth/20 Mass Spring Mechanics/d Only Periclinal Growth in L1', '50', '50', '50', '50, 89, 160, 170, 190', 'Mesh/System/Save', 'OvuleCell2DGrowth_MS-Case2', '200')
